### ISSUE TITLE
WARNING: The Python lzma extension was not compiled. Missing the lzma lib?

### ISSUE THREAD

**Issue by disonwei** [asdf-community/asdf-python#154]
Apple M2  13.2.1 
Try installing python 3.11.2  3.11.1 3.10.10
After installing python, it will appear that lzma is not installed.
Cause scrapy to fail to function properly

Downloading Python-3.10.10.tar.xz...
-> https://www.python.org/ftp/python/3.10.10/Python-3.10.10.tar.xz
Installing Python-3.10.10...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dison/.asdf/installs/python/3.10.10/lib/python3.10/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
WARNING: The Python lzma extension was not compiled. Missing the lzma lib?

**Comment by rolandcrosby** [comment]
I ran into this as well, but was able to solve it by reinstalling Python after installing `xz` via Homebrew. Not sure what to do if you're not using Homebrew.

**Comment by andrewcrook** [comment]
On Mac Homebrew provides xz this is a newer algorithm implementation which has lzma backward compatibility.
xz on Linux should also do the same.

Also on Mac libffi installation seems to be only required for very old versions of python , newer versions seem to have patches applied around ctypes by python-build which is used under pyenv which is used by asdf-paython.

**Comment by Haelle** [comment]
> For Linux (tested with Ubuntu 22.04), you need the following dependencies for asdf-python: `libsqlite3-dev libbz2-dev liblzma-dev libffi-dev`
> 
> I think some form of `tkinter` or `tcl` is also required if you develop GUI apps.

on a brand new computer (ubuntu 22) I forgot what dependencies I needed for Python via ASDF, it would be nice to have it in the README wdyt ?

**Comment by andrewcrook** [comment]
> it would be nice to have it in the README 

There is a link in README.md with a link to system dependencies which covers the various requirements for platforms.

**Comment by khaykingleb** [comment]
@whee hey, have you solved this issue? I'm using Nix as well and wonder if I can avoid installing Homebrew

**Comment by whee** [comment]
> [@whee](https://github.com/whee) hey, have you solved this issue? I'm using Nix as well and wonder if I can avoid installing Homebrew

@khaykingleb no; I gave up on it and started using uv for Python.
